//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMediaPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyMediaTable
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public long ArtistFK { get; set; }
        public long AlbumFK { get; set; }
        public string Genre { get; set; }
        public Nullable<long> Plays { get; set; }
    
        public virtual MyMediaAlbum MyMediaAlbum { get; set; }
        public virtual MyMediaArtist MyMediaArtist { get; set; }
    }
}
